---
  apiVersion: v1
  kind: Service
  metadata:
    name: jenkins-ui
  spec:
    type: LoadBalancer
    ports:
      - port: 80
        name: jenkins-http
        targetPort: 8080
        protocol: TCP
    selector:
      name: jenkins-server

---
  kind: Service
  apiVersion: v1
  metadata:
    name: jenkins-discovery
  spec:
    ports:
      - port: 50000
        name: jenkins-slaves
        targetPort: 50000
        protocol: TCP
    selector:
      name: jenkins-server
